import React, { useEffect, useState } from 'react';
import './Airlines.scss';


const airsData = [
    {
      end_year: "",
      intensity: 4,
      sector: "Energy",
      topic: "energy",
      insight: "Ecological impacts of palm oil expansion in Indonesia",
      url: "http://www.theicct.org/sites/default/files/publications/Indonesia-palm-oil-expansion_ICCT_july2016.pdf",
      region: "South-Eastern Asia",
      start_year: "",
      impact: "",
      added: "July, 17 2016 03:21:18",
      published: "July, 08 2016 00:00:00",
      country: "",
      relevance: 2,
      pestle: "Environmental",
      source: "theicct",
      title: "Without a new vision for biofuel production, there is great risk that this part of Indonesia's renewable energy policy will increase rather than reduce Indonesian emissions.",
      likelihood: 2
    },
    {
      end_year: 2025,
      intensity: 20,
      sector: "Energy",
      topic: "oil",
      insight: "Ecological impacts of palm oil expansion in Indonesia",
      url: "http://www.theicct.org/sites/default/files/publications/Indonesia-palm-oil-expansion_ICCT_july2016.pdf",
      region: "South-Eastern Asia",
      start_year: "",
      impact: "",
      added: "July, 17 2016 03:21:18",
      published: "July, 08 2016 00:00:00",
      country: "",
      relevance: 5,
      pestle: "Industries",
      source: "theicct",
      title: "Total harvested oil palm area in Indonesia grew from 4.1 million ha in 2006 to an estimated 8.9 million ha in 2015 and is projected to reach 17 million ha by 2025.",
      likelihood: 4
    },
    {
      end_year: "",
      intensity: 3,
      sector: "Energy",
      topic: "oil",
      insight: "Ecological impacts of palm oil expansion in Indonesia",
      url: "http://www.theicct.org/sites/default/files/publications/Indonesia-palm-oil-expansion_ICCT_july2016.pdf",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 17 2016 03:21:18",
      published: "July, 08 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "Industries",
      source: "theicct",
      title: "Policies that continue to promote growing for the use of palm and other oils in biofuel will thus likely exceed the capacity of the industry to expand sustainably.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 2,
      sector: "Energy",
      topic: "oil",
      insight: "Ecological impacts of palm oil expansion in Indonesia",
      url: "http://www.theicct.org/sites/default/files/publications/Indonesia-palm-oil-expansion_ICCT_july2016.pdf",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 17 2016 03:21:18",
      published: "July, 08 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "Industries",
      source: "theicct",
      title: "New oil palm plantations sited on degraded or Imperata grasslands could realize significant carbon savings with low biodiversity impacts.",
      likelihood: 2
    },
    {
      end_year: 2019,
      intensity: 6,
      sector: "Energy",
      topic: "energy",
      insight: "Inflation Report – July 2016",
      url: "http://www.nbp.pl/en/publikacje/raport_inflacja/iraport_july2016.pdf",
      region: "World",
      start_year: 2016,
      impact: "",
      added: "July, 17 2016 02:44:19",
      published: "July, 08 2016 00:00:00",
      country: "",
      relevance: 2,
      pestle: "Economic",
      source: "nbp",
      title: "In the coming years the price of energy commodities in the global markets will remain at a moderate level.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 9,
      sector: "Energy",
      topic: "oil",
      insight: "Inflation Report – July 2016",
      url: "http://www.nbp.pl/en/publikacje/raport_inflacja/iraport_july2016.pdf",
      region: "Northern America",
      start_year: "",
      impact: "",
      added: "July, 17 2016 02:44:18",
      published: "July, 08 2016 00:00:00",
      country: "United States of America",
      relevance: 3,
      pestle: "Economic",
      source: "nbp",
      title: "Oil production growth in the OPEC countries will be largely offset by deepening declines in oil production in the United States.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 6,
      sector: "Energy",
      topic: "oil",
      insight: "Inflation Report – July 2016",
      url: "http://www.nbp.pl/en/publikacje/raport_inflacja/iraport_july2016.pdf",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 17 2016 02:44:18",
      published: "July, 08 2016 00:00:00",
      country: "",
      relevance: 2,
      pestle: "Industries",
      source: "nbp",
      title: "In the absence of agreement as to the measures aimed at increasing oil prices, high oil production in the OPEC countries should be expected.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 6,
      sector: "Energy",
      topic: "oil",
      insight: "Inflation Report – July 2016",
      url: "http://www.nbp.pl/en/publikacje/raport_inflacja/iraport_july2016.pdf",
      region: "World",
      start_year: "",
      impact: "",
      added: "July, 17 2016 02:44:17",
      published: "July, 08 2016 00:00:00",
      country: "",
      relevance: 2,
      pestle: "Economic",
      source: "nbp",
      title: "Oil prices in the global markets are expected to stabilise.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 4,
      sector: "",
      topic: "growth",
      insight: "Indonesia's top diesel buyer says biofuel rule unworkable",
      url: "http://sustainability.thomsonreuters.com/2016/07/11/indonesias-top-diesel-buyer-says-biofuel-rule-unworkable/",
      region: "South-Eastern Asia",
      start_year: "",
      impact: "",
      added: "July, 17 2016 02:41:14",
      published: "July, 11 2016 00:00:00",
      country: "Indonesia",
      relevance: 2,
      pestle: "Economic",
      source: "Thomson Reuters ",
      title: "Less-than-expected growth in bio consumption by Indonesia's largest diesel buyer could weigh on palm prices as more supplies are diverted to the global market.",
      likelihood: 2
    },
    {
      end_year: "",
      intensity: 6,
      sector: "",
      topic: "",
      insight: "PIRA Energy Market Recap for the Week Ending July 5, 2016",
      url: "http://www.ssuchronicle.com/2016/07/06/pira-energy-market-recap-for-the-week-ending-july-5-2016/",
      region: "South-Eastern Asia",
      start_year: "",
      impact: "",
      added: "July, 17 2016 02:15:56",
      published: "July, 06 2016 00:00:00",
      country: "",
      relevance: 2,
      pestle: "",
      source: "University Chronicle",
      title: "Vietnam's oil product imports will rise further through next year with growing demand.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 3,
      sector: "Energy",
      topic: "oil",
      insight: "PIRA Energy Market Recap for the Week Ending July 5, 2016",
      url: "http://www.ssuchronicle.com/2016/07/06/pira-energy-market-recap-for-the-week-ending-july-5-2016/",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 17 2016 02:15:56",
      published: "July, 06 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "Industries",
      source: "University Chronicle",
      title: "The economic fallout of Brexit will only potentially delay the pace of oil price recovery and will not derail it.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 16,
      sector: "Energy",
      topic: "oil",
      insight: "PIRA Energy Market Recap for the Week Ending July 5, 2016",
      url: "http://www.ssuchronicle.com/2016/07/06/pira-energy-market-recap-for-the-week-ending-july-5-2016/",
      region: "World",
      start_year: 2017,
      impact: "",
      added: "July, 17 2016 02:15:55",
      published: "July, 06 2016 00:00:00",
      country: "",
      relevance: 4,
      pestle: "Industries",
      source: "University Chronicle",
      title: "Oil prices will move higher as the global stock surplus falls substantively in 2H16 and 2017.",
      likelihood: 4
    },
    {
      end_year: "",
      intensity: "",
      sector: "",
      topic: "",
      insight: "R2P Monitor",
      url: "http://www.globalr2p.org/media/files/r2p_monitor_july2016_final.pdf",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 17 2016 01:51:31",
      published: "July, 15 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "",
      source: "globalr2p",
      title: "Conflicts have the potential to fracture Nigerian society.",
      likelihood: ""
    },
    {
      end_year: 2020,
      intensity: 12,
      sector: "Information Technology",
      topic: "robot",
      insight: "62 market research reports study robotics industry",
      url: "http://robohub.org/62-market-research-reports-study-robotics-industry/",
      region: "",
      start_year: 2016,
      impact: "",
      added: "July, 16 2016 02:44:49",
      published: "July, 11 2016 00:00:00",
      country: "",
      relevance: 3,
      pestle: "Economic",
      source: "Robothub",
      title: "Forecasts the industrial robotics market in APAC to grow at a CAGR of 8.7% during the period 2016-2020 in the top 5 segments.",
      likelihood: 4
    },
    {
      end_year: "",
      intensity: 4,
      sector: "Retail",
      topic: "consumer",
      insight: "Looking For Opportunity In The Heart of Brexit's Power Vacuum",
      url: "http://www.digitalistmag.com/finance/2016/07/12/looking-for-opportunity-in-the-heart-of-brexits-power-vacuum-04315781",
      region: "Europe",
      start_year: "",
      impact: "",
      added: "July, 16 2016 02:24:46",
      published: "July, 12 2016 00:00:00",
      country: "",
      relevance: 2,
      pestle: "Social",
      source: "Digitalist Magazine",
      title: "There is risk for an impact on the general consumer sentiment across Europe.",
      likelihood: 2
    },
    {
      end_year: "",
      intensity: 2,
      sector: "",
      topic: "",
      insight: "Daily Agenda: Bank of England Hold Rates as Pound Spikes",
      url: "http://www.institutionalinvestor.com/article/3570381/banking-and-capital-marketsdaily-agenda/daily-agenda-bank-of-england-hold-rates-as-pound-spikes.html",
      region: "Northern America",
      start_year: "",
      impact: "",
      added: "July, 16 2016 01:28:37",
      published: "July, 14 2016 00:00:00",
      country: "United States of America",
      relevance: 1,
      pestle: "",
      source: "Institutional Investor",
      title: "Fed sees U.S. Brexit risks.",
      likelihood: 2
    },
    {
      end_year: "",
      intensity: 2,
      sector: "Energy",
      topic: "oil",
      insight: "Hot Commodities: One Step Forward, Some Steps Back",
      url: "https://www.lawfareblog.com/hot-commodities-one-step-forward-some-steps-back",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 16 2016 01:16:29",
      published: "July, 13 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "Industries",
      source: "Lawfare",
      title: "Rhetoric promoting the rise in American oil production and related decline in the relevance of Middle Eastern producers (and thus of geopolitical concerns) is misplaced-and in fact quite the opposite could be true.",
      likelihood: 2
    },
    {
      end_year: "",
      intensity: 6,
      sector: "Retail",
      topic: "export",
      insight: "Hot Commodities: One Step Forward, Some Steps Back",
      url: "https://www.lawfareblog.com/hot-commodities-one-step-forward-some-steps-back",
      region: "Northern Africa",
      start_year: "",
      impact: "",
      added: "July, 16 2016 01:16:28",
      published: "July, 13 2016 00:00:00",
      country: "Libya",
      relevance: 2,
      pestle: "Economic",
      source: "Lawfare",
      title: "Libya anticipates it will resume oil exports from the Es Sider and Ras Lanuf oil ports (two of the country's largest) within a week.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 2,
      sector: "Government",
      topic: "government",
      insight: "Oil, Greed, and Grievances in the Middle East and North Africa",
      url: "https://www.newsecuritybeat.org/2016/07/oil-greed-grievances-middle-east-north-africa/",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 16 2016 01:12:21",
      published: "July, 12 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "Political",
      source: "New Security Beat",
      title: "Countries threatened by larger-scale insurgencies might want to consider giving regional groups some share in central government decision-making.",
      likelihood: 2
    },
    {
      end_year: "",
      intensity: 3,
      sector: "Energy",
      topic: "oil",
      insight: "Futureseek Daily Link Review; 11 July 2016",
      url: "https://futureseek.wordpress.com/2016/07/10/futureseek-daily-link-review-11-july-2016/",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 16 2016 00:57:46",
      published: "July, 10 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "Technological",
      source: "Futureseek Link Digest",
      title: "20 times more sensitivity gravity sensor will transform oil discoveries.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 6,
      sector: "Financial services",
      topic: "investment",
      insight: "In World Of $50 Oil, Shale Beats Deepwater",
      url: "http://oilprice.com/Energy/Crude-Oil/In-World-Of-50-Oil-Shale-Beats-Deepwater.html",
      region: "Northern America",
      start_year: "",
      impact: "",
      added: "July, 15 2016 04:21:22",
      published: "July, 13 2016 00:00:00",
      country: "United States of America",
      relevance: 2,
      pestle: "Economic",
      source: "oilprice.com",
      title: "In short, future investment dollars will increasingly find their way into U.S. shale at the expense of deepwater.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 8,
      sector: "Environment",
      topic: "gas",
      insight: "7 companies to watch in carbon capture and storage",
      url: "https://www.greenbiz.com/article/companies-watch-carbon-capture-and-storage",
      region: "Oceania",
      start_year: "",
      impact: "",
      added: "July, 15 2016 03:52:55",
      published: "July, 14 2016 00:00:00",
      country: "",
      relevance: 2,
      pestle: "Environmental",
      source: "GreenBiz",
      title: "Each year 3 to 4 million tons of naturally occurring carbon dioxide produced with the natural gas on Gorgon Island in Western Australia will be captured and injected into a deep sandstone formation around 1.5 miles beneath the island.",
      likelihood: 4
    },
    {
      end_year: "",
      intensity: 2,
      sector: "Energy",
      topic: "oil",
      insight: "Press Release: Diverse Coalition Applauds Introduction of Carbon Capture Incentive Legislation in the U.S. Senate",
      url: "http://www.betterenergy.org/NEORI-Intro-CCS-Leg-Senate-2016",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 14 2016 01:58:49",
      published: "",
      country: "",
      relevance: 1,
      pestle: "Technological",
      source: "betterenergy",
      title: "According to a recent U.S. Department of Energy study, an increased supply of CO2 could enable the EOR industry to produce an additional 21-63 billion barrels of oil with today's technology and store 10-20 billion tons of CO2, or up to four years' worth of national emissions.",
      likelihood: 2
    },
    {
      end_year: "",
      intensity: 16,
      sector: "",
      topic: "gdp",
      insight: "Bank of Canada holds trend setting rate at 0.5%",
      url: "http://www.repmag.ca/news/bank-of-canada-holds-trend-setting-rate-at-0-5-210397.aspx",
      region: "Northern America",
      start_year: 2016,
      impact: "",
      added: "July, 14 2016 01:33:13",
      published: "July, 13 2016 00:00:00",
      country: "",
      relevance: 4,
      pestle: "Economic",
      source: "Real Estate Professional",
      title: "Real GDP in Canada is expected to grow by 1.3% in 2016.",
      likelihood: 4
    },
    {
      end_year: "",
      intensity: 6,
      sector: "Energy",
      topic: "oil",
      insight: "So much for the death of America's bull market. U.S. stocks zoomed to their first record high in more than a year on Monday.",
      url: "http://money.cnn.com/2016/07/11/investing/stocks-record-high-dow-jones-sp-500/index.html",
      region: "Northern America",
      start_year: "",
      impact: "",
      added: "July, 13 2016 02:16:13",
      published: "July, 11 2016 00:00:00",
      country: "United States of America",
      relevance: 2,
      pestle: "Industries",
      source: "CNNMoney",
      title: "Corporate profits are expected to shrink for the fourth-consecutive quarter as the one-two punch of cheap oil and the strong U.S. dollar continue to dent bottom lines.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 6,
      sector: "",
      topic: "material",
      insight: "China's engagement in Africa: From natural resources to human resources",
      url: "http://www.brookings.edu/events/2016/07/13-china-africa-natural-human-resources",
      region: "Eastern Asia",
      start_year: "",
      impact: "",
      added: "July, 13 2016 02:06:12",
      published: "July, 13 2016 00:00:00",
      country: "China",
      relevance: 2,
      pestle: "Industries",
      source: "Brookings Institute",
      title: "China's appetite for raw materials will continue to diminish.",
      likelihood: 3
    },
    {
      end_year: 2017,
      intensity: 16,
      sector: "",
      topic: "economy",
      insight: "Structural Forces Weigh on Future U.S. Growth",
      url: "http://www.imf.org/external/pubs/ft/survey/so/2016/CAR071216A.htm?hootPostID=2f029158f4f3b68339c4e76597056947",
      region: "Northern America",
      start_year: "",
      impact: "",
      added: "July, 13 2016 01:08:54",
      published: "July, 12 2016 00:00:00",
      country: "United States of America",
      relevance: 4,
      pestle: "Economic",
      source: "IMF",
      title: "The U.S. economy is expected to bounce back to 2.5 percent by 2017.",
      likelihood: 4
    },
    {
      end_year: "",
      intensity: 3,
      sector: "Energy",
      topic: "growth",
      insight: "Sensors and Embedded Systems in the Internet of Things (IoT): Market Analysis and Forecasts 2016 - 2021",
      url: "http://www.mindcommerce.com/sensors_and_embedded_systems_in_the_internet_of_things_(iot)_market_analysis_and_forecasts_2016__2021.php?platform=hootsuite",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 12 2016 02:31:47",
      published: "July, 01 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "Economic",
      source: "Mind Commerce",
      title: "Use of IoT and embedded system will be high in EMEA due to positive response to Industrial IoT and growth of embedded systems in electrical grids, automobile and healthcare.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 3,
      sector: "Energy",
      topic: "gas",
      insight: "Low Power Wide Area Network Market Worth 24.46 Billion USD by 2021",
      url: "http://finance.yahoo.com/news/low-power-wide-area-network-143000826.html",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 12 2016 02:04:30",
      published: "July, 11 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "Economic",
      source: "Yahoo Finance",
      title: "Among verticals, oil and gas will lead the LPWAN market with a wide range of organizations adopting LPWAN solutions in all regions.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 24,
      sector: "Energy",
      topic: "oil",
      insight: "John Hofmeister and T. Boone Pickens Discuss Future of U.S. Energy",
      url: "http://www.pickensplan.com/john-hofmeister-and-t-boone-pickens-discuss-future-of-u-s-energy/",
      region: "World",
      start_year: 2016,
      impact: "",
      added: "July, 12 2016 01:40:31",
      published: "July, 08 2016 00:00:00",
      country: "",
      relevance: 6,
      pestle: "Industries",
      source: "Pickens Plan",
      title: "World oil prices will be $80 per barrel by the end of 2016 and will be at or near $100 per barrel by the end of 2017.",
      likelihood: 4
    },
    {
      end_year: "",
      intensity: 3,
      sector: "Energy",
      topic: "oil",
      insight: "The State of World Fisheries and Aquaculture 2016",
      url: "http://www.fao.org/3/a-i5555e.pdf",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 12 2016 01:13:23",
      published: "July, 06 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "Industries",
      source: "FAO",
      title: "Fish oil is expected to be increasingly processed for direct human use as it is considered beneficial for a wide range of biological functions.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 3,
      sector: "Energy",
      topic: "oil",
      insight: "The State of World Fisheries and Aquaculture 2016",
      url: "http://www.fao.org/3/a-i5555e.pdf",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 12 2016 01:13:22",
      published: "July, 06 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "Economic",
      source: "FAO",
      title: "Fishmeal and fish oil will be more frequently used as strategic ingredients to enhance growth at specific stages of fish production.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 3,
      sector: "Energy",
      topic: "oil",
      insight: "The State of World Fisheries and Aquaculture 2016",
      url: "http://www.fao.org/3/a-i5555e.pdf",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 12 2016 01:13:10",
      published: "July, 06 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "Environmental",
      source: "FAO",
      title: "The percentage of fishmeal and fish oil in compound feeds in aquaculture will continue its downward trend.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 3,
      sector: "Manufacturing",
      topic: "production",
      insight: "The State of World Fisheries and Aquaculture 2016",
      url: "http://www.fao.org/3/a-i5555e.pdf",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 12 2016 01:13:07",
      published: "July, 06 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "Environmental",
      source: "FAO",
      title: "Developing countries will maintain their key role in aquaculture production.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 3,
      sector: "Energy",
      topic: "oil",
      insight: "The State of World Fisheries and Aquaculture 2016",
      url: "http://www.fao.org/3/a-i5555e.pdf",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 12 2016 01:12:11",
      published: "July, 06 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "Industries",
      source: "FAO",
      title: "Long-term fish oil prices are not expected revert to lower levels.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 3,
      sector: "Manufacturing",
      topic: "production",
      insight: "The State of World Fisheries and Aquaculture 2016",
      url: "http://www.fao.org/3/a-i5555e.pdf",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 12 2016 01:12:11",
      published: "July, 06 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "Industries",
      source: "FAO",
      title: "Any increase in fishmeal production will need to come from recycling by-products.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 6,
      sector: "",
      topic: "Washington",
      insight: "Saudi Arabia's Quiet Revolution",
      url: "https://rusi.org/publication/newsbrief/saudi-arabia%E2%80%99s-quiet-revolution",
      region: "Western Asia",
      start_year: "",
      impact: "",
      added: "July, 11 2016 03:16:04",
      published: "July, 05 2016 00:00:00",
      country: "Syria",
      relevance: 2,
      pestle: "Political",
      source: "RUSI",
      title: "The fate of Syria will be decided by Moscow and Washington rather than by any of the other diplomatic players.",
      likelihood: 3
    },
    {
      end_year: 2020,
      intensity: 48,
      sector: "Energy",
      topic: "oil",
      insight: "Saudi Arabia's Quiet Revolution",
      url: "https://rusi.org/publication/newsbrief/saudi-arabia%E2%80%99s-quiet-revolution",
      region: "Western Asia",
      start_year: 2016,
      impact: 3,
      added: "July, 11 2016 03:16:03",
      published: "July, 05 2016 00:00:00",
      country: "",
      relevance: 4,
      pestle: "Economic",
      source: "RUSI",
      title: "In Saudi Arabia, non-oil revenue in the next four years is expected to rise from $43 billion to $141 billion.",
      likelihood: 4
    },
    {
      end_year: "",
      intensity: 4,
      sector: "Energy",
      topic: "oil",
      insight: "Iraq: what happened to the oil after the war?",
      url: "https://theconversation.com/iraq-what-happened-to-the-oil-after-the-war-62188",
      region: "Western Asia",
      start_year: "",
      impact: "",
      added: "July, 11 2016 02:27:10",
      published: "July, 08 2016 00:00:00",
      country: "Iraq",
      relevance: 2,
      pestle: "Industries",
      source: "The Conversation",
      title: "Iraq could have become a beacon of oil industry privatisation.",
      likelihood: 2
    },
    {
      end_year: "",
      intensity: "",
      sector: "",
      topic: "market",
      insight: "Hydrocarbon Solvents Market Growth to 2021 Driven by Aliphatic and Paints & Coating Industry",
      url: "http://www.prnewswire.com/news-releases/hydrocarbon-solvents-market-growth-to-2021-driven-by-aliphatic-and-paints--coating-industry-586001681.html",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 11 2016 02:17:13",
      published: "July, 08 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "Economic",
      source: "PR Newswire",
      title: "The hydrocarbon solvents market is forecast to grow at a CAGR of 2.23% during 2016.",
      likelihood: ""
    },
    {
      end_year: "",
      intensity: 12,
      sector: "Energy",
      topic: "oil",
      insight: "Oil's rebound is over, so expect a third-quarter slide: Barclays",
      url: "http://www.cnbc.com/2016/07/08/oils-rebound-is-over-so-expect-a-third-quarter-slide-barclays.html?_source=twitter",
      region: "",
      start_year: 2017,
      impact: "",
      added: "July, 11 2016 01:40:15",
      published: "July, 10 2016 00:00:00",
      country: "",
      relevance: 3,
      pestle: "Industries",
      source: "CNBC ",
      title: "Cohen thinks oil prices will go further down in the third quarter of this year before staging a rebound around the fourth quarter of 2017.",
      likelihood: 4
    },
    {
      end_year: "",
      intensity: 3,
      sector: "Financial services",
      topic: "unemployment",
      insight: "Euro Area At The Crossroads: No Time For Complacency",
      url: "http://www.imf.org/external/pubs/ft/survey/so/2016/CAR070816A.htm?hootPostID=80985784c69193e65dbf320e05b9efe5",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 11 2016 01:32:19",
      published: "July, 08 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "Economic",
      source: "IMF",
      title: "In the Euro area, inflation remains too low, and weak investment, still high unemployment, and the aging of the population will continue to hurt productivity.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 9,
      sector: "",
      topic: "economy",
      insight: "The Global Cyber Game",
      url: "http://static1.squarespace.com/static/570ce46bd51cd428a1ef3190/t/570fb2f3c2ea51967d3e72d9/1460646696585/The%20Global%20Cyber%20Game.pdf",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 10 2016 23:01:08",
      published: "April, 22 2014 00:00:00",
      country: "",
      relevance: 3,
      pestle: "Economic",
      source: "Hardin Tibbs",
      title: "'Information economy' is probably halfway through an S-shaped growth curve and will mature sometime between the 2020s and the 2040s.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 4,
      sector: "Energy",
      topic: "oil",
      insight: "New haze fears as palm oil firms ditch Indonesia pact",
      url: "http://sustainability.thomsonreuters.com/2016/07/05/new-haze-fears-as-palm-oil-firms-ditch-indonesia-pact/",
      region: "South-Eastern Asia",
      start_year: "",
      impact: "",
      added: "July, 10 2016 04:18:39",
      published: "July, 05 2016 00:00:00",
      country: "Indonesia",
      relevance: 2,
      pestle: "Industries",
      source: "Thomson Reuters ",
      title: "Environmentalists have warned of greater risks of haze and forest fires in Southeast Asia after major palm oil firms ditched a landmark \'zero deforestation\' pact in Indonesia..",
      likelihood: 2,
    },
    {
      end_year: "",
      intensity: 6,
      sector: "Energy",
      topic: "oil",
      insight: "Palm oil regaining its competitiveness against soybean oil",
      url: "http://www.theborneopost.com/2016/07/02/palm-oil-regaining-its-competitiveness-against-soybean-oil/",
      region: "Northern America",
      start_year: "",
      impact: "",
      added: "July, 10 2016 04:18:31",
      published: "July, 01 2016 00:00:00",
      country: "United States of America",
      relevance: 2,
      pestle: "Industries",
      source: "BorneoPost Online",
      title: "The higher US dollar/ringgit rate improves CPO competitiveness against soybean oil (which is priced in US dollar) as CPO price (when translated to US dollar) will be lower.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 6,
      sector: "Energy",
      topic: "oil",
      insight: "Palm oil regaining its competitiveness against soybean oil",
      url: "http://www.theborneopost.com/2016/07/02/palm-oil-regaining-its-competitiveness-against-soybean-oil/",
      region: "World",
      start_year: "",
      impact: "",
      added: "July, 10 2016 04:18:31",
      published: "July, 01 2016 00:00:00",
      country: "",
      relevance: 2,
      pestle: "Economic",
      source: "BorneoPost Online",
      title: "Palm oil is regaining its competitiveness level against soybean oil and it will likely win global market share of vegetable oils going forward.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 2,
      sector: "Environment",
      topic: "pollution",
      insight: "July 7, 2016",
      url: "http://www.worldhealth.net/newsletter/20160707_NEWS/",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 10 2016 03:43:03",
      published: "",
      country: "",
      relevance: 1,
      pestle: "Environmental",
      source: "World Health",
      title: "Levels of air pollution within European recommended levels have been linked to an increased risk of severe heart attack.",
      likelihood: 2
    },
    {
      end_year: 2025,
      intensity: 16,
      sector: "Energy",
      topic: "oil",
      insight: "Peak Oil Review - July 4 2016",
      url: "http://www.resilience.org/stories/2016-07-04/peak-oil-review-july-4-2016",
      region: "Northern America",
      start_year: "",
      impact: "",
      added: "July, 10 2016 02:19:36",
      published: "July, 04 2016 00:00:00",
      country: "Canada",
      relevance: 4,
      pestle: "Industries",
      source: "Resilience",
      title: "Canada's oil sands production will grow by 42 percent to 3.4 million barrels per day by 2025.",
      likelihood: 4
    },
    {
      end_year: "",
      intensity: 48,
      sector: "Manufacturing",
      topic: "car",
      insight: "Peak Oil Review - July 4 2016",
      url: "http://www.resilience.org/stories/2016-07-04/peak-oil-review-july-4-2016",
      region: "Southern Asia",
      start_year: "",
      impact: 3,
      added: "July, 10 2016 02:19:34",
      published: "July, 04 2016 00:00:00",
      country: "India",
      relevance: 4,
      pestle: "Social",
      source: "Resilience",
      title: "India's $13 billion pay increase for federal employees will boost car and motorcycle purchases.",
      likelihood: 4
    },
    {
      end_year: "",
      intensity: 4,
      sector: "Financial services",
      topic: "money",
      insight: "Peak Oil Review - July 4 2016",
      url: "http://www.resilience.org/stories/2016-07-04/peak-oil-review-july-4-2016",
      region: "Western Asia",
      start_year: "",
      impact: "",
      added: "July, 10 2016 02:19:30",
      published: "July, 04 2016 00:00:00",
      country: "",
      relevance: 2,
      pestle: "Economic",
      source: "Resilience",
      title: "Investing large amounts of money in the volatile Middle East carries considerable political risk.",
      likelihood: 2
    },
    {
      end_year: "",
      intensity: 4,
      sector: "Energy",
      topic: "oil",
      insight: "Environmental Peacebuilding Update",
      url: "http://www.environmentalpeacebuilding.org/assets/NewsletterPDFArchive/EP-Update-Issue-65.pdf",
      region: "Southern Asia",
      start_year: "",
      impact: "",
      added: "July, 10 2016 02:09:53",
      published: "July, 05 2016 00:00:00",
      country: "",
      relevance: 2,
      pestle: "Political",
      source: "environmentalpeacebuilding",
      title: "Iran and the Kurdistan Regional Government (KRG) have hammered out the technical details of a plan to build a pipeline that could transfer as much as 250,000 barrels a day of Kurdish oil to Iran.",
      likelihood: 2
    },
    {
      end_year: "",
      intensity: 3,
      sector: "",
      topic: "",
      insight: "Greener Earth News",
      url: "http://www.greenerearthnews.com/index.php/2016/07/",
      region: "South-Eastern Asia",
      start_year: "",
      impact: "",
      added: "July, 10 2016 02:09:42",
      published: "July, 09 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "",
      source: "greenerearthnews",
      title: "The forests of Indonesia and Malaysia are projected to disappear completely in 20 years if deforestation is not curbed.",
      likelihood: 3
    },
    {
      end_year: "",
      intensity: 2,
      sector: "Energy",
      topic: "oil",
      insight: "Greener Earth News",
      url: "http://www.greenerearthnews.com/index.php/2016/07/",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 10 2016 02:09:42",
      published: "July, 09 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "Industries",
      source: "greenerearthnews",
      title: "Experts have pinpointed the destruction of Sumatran and Bornean rainforests in order to produce palm oil as one of the greatest threats to orangutan survival.",
      likelihood: 2
    },
    {
      end_year: "",
      intensity: 12,
      sector: "",
      topic: "",
      insight: "3 rd Global Geologists Annual Meeting July 18-19, 2016 Brisbane, Australia",
      url: "http://annualmeeting.conferenceseries.com/geologists/",
      region: "Asia",
      start_year: 2020,
      impact: "",
      added: "July, 10 2016 01:57:42",
      published: "July, 11 2016 00:00:00",
      country: "",
      relevance: 3,
      pestle: "",
      source: "conferenceseries",
      title: "Iron ore consumption in Asia is expected to increase at a CAGR of 5.2% to reach 2.6 billion metric tons in 2020.",
      likelihood: 4
    },
    {
      end_year: "",
      intensity: 2,
      sector: "Energy",
      topic: "gas",
      insight: "Guide to NT Petroleum Environment Regulations 2016",
      url: "https://nt.gov.au/__data/assets/pdf_file/0005/295907/guide-to-nt-petroleum-environment-regulations-2016.pdf",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 10 2016 01:55:59",
      published: "July, 05 2016 00:00:00",
      country: "",
      relevance: 1,
      pestle: "Industries",
      source: "Australian Government",
      title: "Objective-based regulation is considered to be the most suitable form of regulation to manage the environmental risks associated with oil and gas activities.",
      likelihood: 2
    },
    {
      end_year: 2026,
      intensity: 4,
      sector: "",
      topic: "",
      insight: "Lower methane emissions, kick your beef habit",
      url: "http://www.dailytexanonline.com/2016/07/03/lower-methane-emissions-kick-your-beef-habit",
      region: "Northern America",
      start_year: 2016,
      impact: "",
      added: "July, 10 2016 01:44:40",
      published: "July, 03 2016 00:00:00",
      country: "United States of America",
      relevance: 1,
      pestle: "",
      source: "dailytexanonline",
      title: "U.S. beef consumption is forecasted to decrease by three percent over the next decade.",
      likelihood: 4
    },
    {
      end_year: 2021,
      intensity: 6,
      sector: "Energy",
      topic: "energy",
      insight: "Strong Growth Ahead for Lithium Ion Battery Market",
      url: "https://epsnews.com/2016/07/06/lithium-ion-battery-market/",
      region: "World",
      start_year: 2016,
      impact: "",
      added: "July, 10 2016 01:30:45",
      published: "July, 06 2016 00:00:00",
      country: "",
      relevance: 2,
      pestle: "Economic",
      source: "EPS News",
      title: "Anticipated growth in global energy demand is expected to boost adoption of lithium-ion batteries over the course of next five years.",
      likelihood: 3
    },
    {
      end_year: 2020,
      intensity: 12,
      sector: "Energy",
      topic: "oil",
      insight: "Strong Growth Ahead for Lithium Ion Battery Market",
      url: "https://epsnews.com/2016/07/06/lithium-ion-battery-market/",
      region: "",
      start_year: "",
      impact: "",
      added: "July, 10 2016 01:30:44",
      published: "July, 06 2016 00:00:00",
      country: "",
      relevance: 3,
      pestle: "Industries",
      source: "EPS News",
      title: "Demand for energy is forecast to increase from 12,928.4 Million Ton Oil Equivalent (MTOE) in 2014 to 17,000 MTOE by 2020.",
      likelihood: 4
    }
  ]

const Airlines = () => {

    // all states
    // const [airsData, setAirsData] = useState([]);
    const [filterAirsData, setFilterAirsData] = useState([]);
    const [checkboxValue, setCheckboxValue] = useState('');

    // jsonp data management
    useEffect(()=>{

    },[]);


    // checkboxValue
    useEffect(()=>{
            const newAirsData = airsData.filter(data=>data?.alliance===`${checkboxValue==='' ? 'none' || 'ST' || 'OW' || 'SA' : checkboxValue}`);
            setFilterAirsData(newAirsData);
    },[checkboxValue])
    
    
    // checkbox Management
    const handleCheckBox = (e) =>{
        if(e.target.checked){
            setCheckboxValue(e.target.value)
        }
        else{
            setCheckboxValue('')
        }
    }
    
    

    return (
        <div className='mainContainer'>
            <h2 className='airlines'>Airlines</h2>   
            <h6 className='alliance'>Filter by Alliances</h6>

            {/* filtering section */}
            <div className='checkboxValue'>
                <div className='inputDiv'>
                    <input onChange={handleCheckBox} type="checkbox" id="oneWorld" name="oneWorld" value="OW" checked={checkboxValue=== "OW" ? true : false}/>
                    <label htmlFor="oneWorld">Oneworld</label>
                </div>
                <div className='inputDiv'>
                    <input onChange={handleCheckBox} type="checkbox" id="skyTeam" name="skyTeam"  value="ST" checked={checkboxValue=== "ST" ? true : false}/>
                    <label htmlFor="skyTeam">Sky Team</label>
                </div>
                <div className='inputDiv'>
                    <input onChange={handleCheckBox} type="checkbox" id="starAlliance" name="starAlliance" value="SA" checked={checkboxValue=== "SA" ? true : false}/>
                    <label htmlFor="starAlliance">Star Alliance</label>
                </div>
            </div>

            {/* card section */}
            <div className='gridContainer'>
                {airsData.slice(0, 12).map((air, index)=>
                <div   className='gridItem'>
                    {/* <img style={{width:'32px',height:'32px'}} src={`https://www.kayak.com${air?.logoURL}`} alt=''/> */}
                    {/* <div className='itemName'>
                        <h3>{air?.name} name</h3>
                    </div> */}
                    <div className='itemDetails'>
                        <p className='airsName'>country: {air?.country} </p>
                        <p className='airsUrl'>Region: {air?.region} </p>
                        <p className='airsUrl'>Topic: {air?.topic} </p>
                        <h3 className='airsName'> Intensity: {air?.intensity} </h3>
                        <p className='airsAlliance'>Likelihood: {air?.likelihood} </p>
                        <p className='airsPhone'>Relevance: {air?.relevance} </p>
                        {/* <p className='airsUrl'> {air?.city} </p> */}
                    </div>
                </div>
                )}
            </div>
        </div>
    );
};

export default Airlines;